name: Code Quality
run-name: ${{ github.actor }} is checking code Quality

on:
  pull_request:          # Era "pull request:" y con un espacio
    branches:
      - main             # Era "-main" sin espacio

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # Debe ir antes de run; versión estable es v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v3  # Última versión a día de hoy [web:24][web:30]

      - name: Install the project
        run: uv sync --locked --all-extras --dev
        shell: bash

      - name: Run tests
        run: uv run pytest tests
        shell: bash
