name: Code Quality
run-name: ${{ github.actor }} is checking code quality

on:
  pull_request:
    branches:
      - main

jobs:
  code-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install the project
        run: uv sync --locked --all-extras --dev
        shell: bash
  check-linter:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4

     - uses: ./.github/actions/setup-python-uv

     - run: uv run ruff check .

     - uses: ./.github/actions/minimize-uv-cache

  check-formatter:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4

     - uses: ./.github/actions/setup-python-uv

     - run: uv run ruff format .

     - uses: ./.github/actions/minimize-uv-cache

  check-type-safety:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - uses: ./.github/actions/setup-python-uv

     - run: uv run pyright

     - uses: ./.github/actions/minimize-uv-cache

  run-unit-tests:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - uses: ./.github/actions/setup-python-uv

     - run: uv run pytest

     - uses: ./.github/actions/minimize-uv-cache


