name: ðŸ”Ž Code Safety
run-name: Running Code Safety for ${{ github.ref }} on ${{ github.event_name }} ðŸ”Ž

on:
  pull_request:
    branches:
      - main

jobs:
  check-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - uses: astral-sh/setup-uv@v3

      - run: uv sync --locked
        shell: bash

      - run: uv run ruff check .
        shell: bash

  check-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - uses: astral-sh/setup-uv@v3

      - run: uv sync --locked
        shell: bash

      - run: uv run ruff format .
        shell: bash

  check-type-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - uses: astral-sh/setup-uv@v3

      - run: uv sync --locked
        shell: bash

      - run: uv run pyright
        shell: bash

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - uses: astral-sh/setup-uv@v3

      - run: uv sync --locked
        shell: bash

      - run: uv run pytest
        shell: bash
